trigger:
- main  # hoặc master, nếu repo bạn dùng nhánh đó

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "No build script found"
  displayName: 'Build project'

- script: echo " Build completed successfully!"
  displayName: 'Success message'
