trigger:
- master

pool:
  name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14'

- script: |
    npm install
  displayName: 'Install dependencies'

# Chạy thử server để đảm bảo không lỗi cú pháp
- script: |
    npm start || echo "Server start failed, but continuing for lab purpose"
  continueOnError: true
  displayName: 'Start server (test)'

- script: echo "✅ Pipeline ran successfully for Express backend!"
  displayName: 'Success message'
